export const COURS_LOGOS: { [key:string]:string} = {
"HTML":"/logoimagen.png",
"CSS":"/cssl.png",
"JavaScript":"/jslogo.png",
"TypeScript":"/tslogo.png",
"C#":"/csharp.png",
"Java":"/javalogo.png",
"Python":"/pyton.png",
"PHP":"/phplogo.png",
"Ruby":"/ruby.jpg",
"Go (Golang)":"/gol.png",
"SQL":"/sqlLogo.png",
"NoSQL":"/no-sql-logo.png", 
"Swift":"/logoswift.png",
"Kotlin":"/kotlin.png",
"Dart":"/dart.png",
"React Native":"/logoreact.png",
"React Native js":"/reactjs.jpeg",
"C":"/cLang.png",
"C++":"/cLang.png",
"Rust":"/rust.jpg",
"R":"/Rprogr.png",
"Julia":"/julilogo.png",
"Shell/Bash Scripting":"/shell.png",
"PowerShel":"/powershell.png",

}